[package]
name = "modelator"
version = "0.1.0"
authors = ["Andrey Kuprianov <andrey@informal.systems>"]
edition = "2018"


[dependencies.clap]
git = "https://github.com/clap-rs/clap"
rev = "cf4881182abf45ad755fa8eb14cca044948d87c2"
