[package]
name = "tester"
version = "0.1.0"
authors = ["Andrey Kuprianov <andrey@informal.systems>"]
edition = "2018"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
simple-error = "0.2.1"
tempfile = "3.1.0"

