[package]
name = "modelator"
version = "0.1.0"
authors = ["Vitor Enes <vitorenesduarte@gmail.com>", "Andrey Kuprianov <andrey@informal.systems>"]
edition = "2018"

[dependencies]
clap = "3.0.0-beta.2"
nom = "6.1.2"
rand = "0.8.3"
reqwest = { version = "0.11.1", features = ["blocking"] }
serde = { version = "1.0.123", features = ["derive"] }
serde_json = "1.0.62"
thiserror = "1.0.24"
tracing = "0.1.25"
paste = "1.0"
seq-macro = "0.2.1"

[dev-dependencies]
quickcheck = "1.0.3"
quickcheck_macros = "1.0.0"
