name: Release

on:
  pull_request:
    branches: [main]
    types: [closed]

env:
  GOLANG_DIR: go
  PYTHON_DIR: py
  RUST_DIR: rs

jobs:
  github-release:
    environment: Release
    runs-on: ubuntu-latest
    if: startsWith(github.event.pull_request.title, '[RELEASE] ') &&
      github.event.pull_request.merged == true
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - name: Configure Git
        run: |
          git config --global user.name "$GITHUB_ACTOR"
          git config --global user.email "github@actions.ci"

      - name: Add local bin paths
        run: |
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install Rust stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Install Rust-Cache for Github actions
        uses: Swatinem/rust-cache@v1
        with:
          working-directory: ${{ env.RUST_DIR }}

      - name: Install `quickinstall`
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-quickinstall

      - name: Install `unclog`
        uses: actions-rs/cargo@v1
        with:
          command: quickinstall
          args: unclog

      - name: Parse release version
        run: |
          echo "RELEASE_VERSION=`sed 's/^\[RELEASE\] v//g' <<< "${{ github.event.pull_request.title }}"`" >> $GITHUB_ENV

      - name: Tag on main and make a Github release
        run: ./scripts/github_release.sh

      - name: Install Rust stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Rust publish
        working-directory: ${{ env.RUST_DIR }}
        run: |
          cargo publish --token ${{ secrets.CRATES_IO_TOKEN }}

      - name: Setup Go
        uses: actions/setup-go@v2

      - name: Golang publish
        working-directory: ${{ env.GOLANG_DIR }}
        run: |
          # GOPROXY=proxy.golang.org go list -m github.com/${{ github.repository }}/$GOLANG_DIR@v$RELEASE_VERSION
          echo "Skipping Go package"

      - name: Setup Python
        uses: actions/setup-python@v1

      - name: Setup Poetry
        uses: Gr1N/setup-poetry@v7

      - name: Poetry publish
        working-directory: ${{ env.PYTHON_DIR }}
        run: |
          # poetry publish --build
          echo "Skipping Python package"
